name: work_manager_server
description: Starting point for a Serverpod server.
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  mailer: ^6.3.0
  serverpod: 2.9.1
  serverpod_auth_server: 2.9.1
dev_dependencies:
  lints: ^6.0.0
  serverpod_test: 2.9.1
  test: '^1.24.2'

