# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  gmailEmail: 'halowebhook@gmail.com'
  gmailPassword: 'jopd cqdy htev zohr '

# These are passwords used when running the server locally in development mode
development:
  database: 'mXnoRZ0jC-8QNDLuZkz6aVAUqgr9Vw-M'
  redis: 'WhafIs0e1gW-Udp2yMV-EYsG61eVI3SY'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'BcZQKCacvIdHTzKX4ne47UCXaRerQF76'

test:
  database: 'zodnjkO3MRXrpgy1RzBSKuh-AH6nN3yQ'
  redis: 'IyMPMLWQr0KvGaG7H2wGOsqWuR3snYXS'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: '68sSaWphw1z1jMPODFB_ctTlkje4SC7l'
  serviceSecret: '-RGXiaPkHpNblw0tsybYlrq9SliOyVOG'

# Passwords used in production mode.
production:
  database: 'PidEDQ1MJ8jwC_RUk-9S67HuJ9ss2AUg'
  serviceSecret: '1cFYjWXVcljz4KLiA8IZu5yNsRnCLMqJ'
