name: work_manager_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies:
  flutter:
    sdk: flutter
  serverpod_auth_shared_flutter: 2.3.1
  serverpod_flutter: 2.3.1
  work_manager_client:
    path: ../work_manager_client
dev_dependencies:
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
